/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.solovyev.android;

public final class R {
    public static final class attr {
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int boundaries=0x7f010007;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int directionTextAlpha=0x7f010005;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int directionTextScale=0x7f010004;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int hTextPosition=0x7f010006;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int steps=0x7f010008;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textDown=0x7f010001;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textLeft=0x7f010003;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textRight=0x7f010002;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textUp=0x7f010000;
    }
    public static final class color {
        public static final int button_ce_text_color=0x7f030003;
        public static final int button_operator_text_color=0x7f030002;
        public static final int button_text_color=0x7f030001;
        public static final int default_background=0x7f030006;
        public static final int default_text_color=0x7f030004;
        public static final int magic_flame=0x7f030000;
        public static final int selected_angle_unit_text_color=0x7f030005;
    }
    public static final class drawable {
        public static final int seek_thumb_normal=0x7f020000;
        public static final int seek_thumb_pressed=0x7f020001;
        public static final int system_copy=0x7f020002;
        public static final int system_delete=0x7f020003;
        public static final int system_kb_delete_dark=0x7f020004;
        public static final int system_kb_delete_light=0x7f020005;
        public static final int system_paste=0x7f020006;
        public static final int timepicker_down_btn=0x7f020007;
        public static final int timepicker_down_disabled=0x7f020008;
        public static final int timepicker_down_disabled_focused=0x7f020009;
        public static final int timepicker_down_normal=0x7f02000a;
        public static final int timepicker_down_pressed=0x7f02000b;
        public static final int timepicker_down_selected=0x7f02000c;
        public static final int timepicker_input=0x7f02000d;
        public static final int timepicker_input_disabled=0x7f02000e;
        public static final int timepicker_input_normal=0x7f02000f;
        public static final int timepicker_input_pressed=0x7f020010;
        public static final int timepicker_input_selected=0x7f020011;
        public static final int timepicker_up_btn=0x7f020012;
        public static final int timepicker_up_disabled=0x7f020013;
        public static final int timepicker_up_disabled_focused=0x7f020014;
        public static final int timepicker_up_normal=0x7f020015;
        public static final int timepicker_up_pressed=0x7f020016;
        public static final int timepicker_up_selected=0x7f020017;
    }
    public static final class string {
        public static final int app_name=0x7f040006;
        public static final int p_drag_angle=0x7f040003;
        public static final int p_drag_angle_key=0x7f040002;
        public static final int p_drag_distance=0x7f040001;
        public static final int p_drag_distance_key=0x7f040000;
        public static final int p_drag_duration=0x7f040005;
        public static final int p_drag_duration_key=0x7f040004;
    }
    public static final class styleable {
        /** Attributes that can be used with a DirectionDragButton.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #DirectionDragButton_directionTextAlpha org.solovyev.android:directionTextAlpha}</code></td><td></td></tr>
           <tr><td><code>{@link #DirectionDragButton_directionTextScale org.solovyev.android:directionTextScale}</code></td><td></td></tr>
           <tr><td><code>{@link #DirectionDragButton_textDown org.solovyev.android:textDown}</code></td><td></td></tr>
           <tr><td><code>{@link #DirectionDragButton_textLeft org.solovyev.android:textLeft}</code></td><td></td></tr>
           <tr><td><code>{@link #DirectionDragButton_textRight org.solovyev.android:textRight}</code></td><td></td></tr>
           <tr><td><code>{@link #DirectionDragButton_textUp org.solovyev.android:textUp}</code></td><td></td></tr>
           </table>
           @see #DirectionDragButton_directionTextAlpha
           @see #DirectionDragButton_directionTextScale
           @see #DirectionDragButton_textDown
           @see #DirectionDragButton_textLeft
           @see #DirectionDragButton_textRight
           @see #DirectionDragButton_textUp
         */
        public static final int[] DirectionDragButton = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005
        };
        /**
          <p>This symbol is the offset where the {@link org.solovyev.android.R.attr#directionTextAlpha}
          attribute's value can be found in the {@link #DirectionDragButton} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:directionTextAlpha
        */
        public static final int DirectionDragButton_directionTextAlpha = 5;
        /**
          <p>This symbol is the offset where the {@link org.solovyev.android.R.attr#directionTextScale}
          attribute's value can be found in the {@link #DirectionDragButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:directionTextScale
        */
        public static final int DirectionDragButton_directionTextScale = 4;
        /**
          <p>This symbol is the offset where the {@link org.solovyev.android.R.attr#textDown}
          attribute's value can be found in the {@link #DirectionDragButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:textDown
        */
        public static final int DirectionDragButton_textDown = 1;
        /**
          <p>This symbol is the offset where the {@link org.solovyev.android.R.attr#textLeft}
          attribute's value can be found in the {@link #DirectionDragButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:textLeft
        */
        public static final int DirectionDragButton_textLeft = 3;
        /**
          <p>This symbol is the offset where the {@link org.solovyev.android.R.attr#textRight}
          attribute's value can be found in the {@link #DirectionDragButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:textRight
        */
        public static final int DirectionDragButton_textRight = 2;
        /**
          <p>This symbol is the offset where the {@link org.solovyev.android.R.attr#textUp}
          attribute's value can be found in the {@link #DirectionDragButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:textUp
        */
        public static final int DirectionDragButton_textUp = 0;
        /** Attributes that can be used with a DragButton.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #DragButton_hTextPosition org.solovyev.android:hTextPosition}</code></td><td></td></tr>
           </table>
           @see #DragButton_hTextPosition
         */
        public static final int[] DragButton = {
            0x7f010006
        };
        /**
          <p>This symbol is the offset where the {@link org.solovyev.android.R.attr#hTextPosition}
          attribute's value can be found in the {@link #DragButton} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:hTextPosition
        */
        public static final int DragButton_hTextPosition = 0;
        /** Attributes that can be used with a NumberRangeSeekBar.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #NumberRangeSeekBar_boundaries org.solovyev.android:boundaries}</code></td><td></td></tr>
           <tr><td><code>{@link #NumberRangeSeekBar_steps org.solovyev.android:steps}</code></td><td></td></tr>
           </table>
           @see #NumberRangeSeekBar_boundaries
           @see #NumberRangeSeekBar_steps
         */
        public static final int[] NumberRangeSeekBar = {
            0x7f010007, 0x7f010008
        };
        /**
          <p>This symbol is the offset where the {@link org.solovyev.android.R.attr#boundaries}
          attribute's value can be found in the {@link #NumberRangeSeekBar} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:boundaries
        */
        public static final int NumberRangeSeekBar_boundaries = 0;
        /**
          <p>This symbol is the offset where the {@link org.solovyev.android.R.attr#steps}
          attribute's value can be found in the {@link #NumberRangeSeekBar} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:steps
        */
        public static final int NumberRangeSeekBar_steps = 1;
    };
}
